### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by reynir** [dren-dk/DontBeADick#1]
I have looked a bit at `encrypt` and `rekey`. I have found some issues and have some questions. I am not a cryptographer.

* The (old) passphrase file is not zeroed when rekeying
* Storing the passphrase on a RAM disk seems **super** sketchy to me - unrelated process could possibly read it, who knows what caching the OS might do, etc.
* Generating a passphrase instead of a secret key seems less than idea. The entropy could potentially be less if the hash is imperfect. I'm not sure it's a big issue, but it's simpler anyway to generate the secret key directly. This will also make `ssss` require less entropy potentially making the `/dev/urandom` patch unnecessary.
* I haven't understood why, but apparently it's best if the secret being shared is random. The secret being shared is a hexadecimal string. See https://media.ccc.de/v/34c3-8885-we_should_share_our_secrets
* What is the gpg passphrase used for? As far as I can read only public keys are stored - then what is the password for?

In recent openssh version you can use the `restrict` option for the key instead of enumerating all `no-foo` options. It should be forward compatible w.r.t. new options.

**Comment by RubyMoonProductionCo** [comment]
i want my fucking life back!
